### 161006 출장시 내 디바이스 찾기...

Date: 2016-10-06<br>
Writer: Sundong Kim<br>

16년 10월 06일 코오롱스포츠 문정직영점 출장 때 디바이스를 4개 가지고 갔었다. (핸드폰, 아이패드1미니, 갤럭시탭 2개)
방문한 시각: 13시 13분 경 을 기준으로 하여 4개 디바이스의 trajectory를 가지는지 판단하고자 하여 이 note를 만듦.

사실 핸드폰은 계속 들고 다녔고(와이파이를 일부러 껐다 켰다 해봄), 패드들은 가방 안에 같이 보관되어 있었음.


### 결론
160928: 아직은 내 device 를찾지 못하였다...
160929: device를 찾았다. deny=True에 존재했다.


### 찾기 위한 노력
조이(ZOYI - Wi-Fi 수신기 제조업체 1644-4052)에 전화: ZOYI Wi-Fi 수신기를 이용하는 코오롱 매장 데이터를 분석하고 있는 카이스트 xxx 입니다. API를 통해 제공되는 json형식의 파일을 이해하는데 도움이 필요한데 담당자와 연결시켜 주실 수 있으신가요? 

담당자분이 직접 핸드폰으로 연락주신다고 하심 (통화: Analyst 유인제씨 - iron@zoyi.yo, 010-2726-2790와 통화)

0. 소속 말하기 - 카이스트 산업공학과 이재길교수님 연구실 박사과정 김선동입니다. 
1. 매장 내부의 움직임 분석해서 고객들의 재방문을 의도하는가 연구를 진행중입니다.
2. 현재 분석하고 있는 데이터는 코오롱 문정점인데, json형식의 데이터를 이해하는데 도움이 필요해서 전화를 드렸다.
3. 코오롱 방문해 보니, zoyi wi-fi 기계로 방문자들이 와이파이를 사용하는건 아니고 트래킹 용인거 같은데, dwell_time이 어떻게 정의되는 지 궁금: Wi-Fi AP와 수신 가능한 상태 시간 을 의미하는 건지 궁금. 특정 시점에 한 군데의 Wi-Fi 수신기와 접속중이 아니라 여러 군데에 연결 가능한 상태일 수 있다
    * 센서에 인터넷이 연결되지 않아도 수집을 수집할 수 있다. 
    * Dwell time: 센서가 맨 처음 수집한 시간과 맨 마지막 시간의 차이. 
4. device_id가 핸드폰 맥 어드레스라고 들었습니다, 핸드폰의 Wi-Fi 맥어드레스는 C4:9A:33:1A:23:FT 이런식으로 생겼는데, 이것과 '4cfef2077e81acfb7e8ed5f266408f7e' 이런 형식의 데이터가 일치하지 않아서 여기에 다른 인코딩 등이 들어가나 궁금합니다.
    * 맥 어드레스는 개인 정보이기 때문에, 수집한 후 바로 hash화 시켜서 저장함. 로직은 복호화시키는 과정이기 때문에 말할 수는 없다. 다만 하나의 맥 어드레스는 하나의 device id이다.
5. Wi-Fi 수신기가 세부 구역별로(1층에 3개, 2층에 3개, 총 6개) 설치되어 있던데, 로그에 찍히는 구역은 out, in, 1f, 2f, 3f, 1f세부 3개, 2f세부 3개  - 매장 전체를 아우르는 in, 유동인구: 센서하나에서 여러 가지 크기의 영역 반지름에 따른  원의 크기. out는 여러 대에 
    * 각 센서는 여러 거리별로(예: 1m, 2m, 3m) 디바이스와 접촉할 수 있고, 그에 따라 세부존, 중간존, 매장 출입, 유동인구에 대한 분석을 수행한다. 
    * 세부 존: 1f inner 센서가 device와 처음 접촉한 순간이 ts, (접촉이 끝난 순간 - 처음 접촉한 순간)이 dwell_time.
    * 좀더 큰 존: 1f의 경우에는 3개의 센서가 특정 거리에 대해 처음 디텍팅된 시간부터 마무리된 순간까지를 1f로 나타냄
    * in과 out: 모든 센서들을 통틀어 분석하는데, 매장 입구에 해당되는 거리 이상에 닿은 순간부터 떨어진 순간까지를 in으로 판단, out의 경우는 유동 인구 체크하려고 좀더 거리를 넓혀서 같은 분석을 수행
6. 직원 deny=True 한번 직원은 영원한 직원은 아님? 
    * deny의 경우 매일 매일 재계산을 함.
    * 로직: deny=True인 건, 2주동안 10회 이상 방문 or 한번 방문했을 때 체류시간이 1시간 이상. 그러면 deny라고 설정해준다. 주변 매장 직원의 경우에도 out 센서에 접촉 가능한 빈도가 2주동안 10회 이상이면 deny로 체크
7. 메일로 웬만한건 물어보면 될 듯.(유인재: iron@zoyi.co), 방문은 지양하나 필요하다면 스케쥴을 확인해봄

최근 데이터 소량 크롤링(crawler.ipynb 참고하여 만듦)

In [1]:
### import libraries
import urllib.request, json, re
import pandas as pd
import datetime
import time, calendar

In [87]:
urlstrip1 = "http://walkinsights.com/api/v1/shops/786/sessions?"
urlstrip2 ="limit=1000&user_token=77eFJPB37UkgYyLjWZrx&user_email=jeeyeachung@kolon.com"
url = urlstrip1 + urlstrip2
response = urllib.request.urlopen(url)
str_response = response.read().decode('utf-8')
obj = json.loads(str_response)

In [88]:
ts = obj['since']
ts

'7fea86b665bf7e15:1f-left'

In [89]:
with open('../data/786_161005_sample/786_'+ts+'.json', 'w') as f:
    json.dump(obj, f)
f.close()

In [91]:
while(True):
    urlstrip3 = "since="+ts+"&limit=1000&"
    url = urlstrip1 + urlstrip3 + urlstrip2
    response = urllib.request.urlopen(url)
    str_response = response.read().decode('utf-8')
    obj2 = json.loads(str_response)
    filename = '../data/786_161005_sample/786_'+ts+'.json'
    with open(filename, 'w') as f:
        json.dump(obj2, f)
    f.close()
    ts = ts = obj2['since']

In [2]:
import glob
import os

In [3]:
contents = []
files = glob.glob('../data/786_161005_sample/*.json')
for filename in files:
    with open(filename, 'r') as f:
        d = json.load(f)
        contents.extend(d['sessions'])

df = pd.DataFrame(contents)

In [4]:
df.to_pickle("../data/786_161005_sample/786_161005_sample.p")

Read & Analyze

In [5]:
### import libraries
import pandas as pd
import datetime
import numpy as np
import re

In [6]:
df = pd.read_pickle("../data/786_161005_sample/786_161005_sample.p")
df.head(5)   ### Show raw data

,area,deny,device_id,dwell_time,key,revisit_count,revisit_period,ts
0,1f-left,NaN,5d9884b5f69ed4381f64636502fbb49b,0,786:7fea86b665bf7e15:1f-left,NaN,NaN,1475666879496
1,out,NaN,a005a99c320acabaed202e97af035d60,38,786:7fea86b66628ee73:out,NaN,NaN,1475666877809
2,2f-left,NaN,47cbc1c26d0aa075de241967ac014e51,359,786:7fea86b667a38ff2:2f-left,NaN,NaN,1475666871751
3,out,NaN,6e06ae972aa58dc4cec4612581c52ab5,46,786:7fea86b667e97cb2:out,NaN,NaN,1475666870632
4,out,NaN,b336d82b169c78b3489aeb37abfdbbbb,13,786:7fea86b668984e6b:out,NaN,NaN,1475666867835

In [22]:
# df = df.loc[(df.ts > 1475661600000) & (df.ts > 1475683200000)]  # 2016년 10월 5일 오전 9시 - 오후 4시 사이
# df.shape

In [7]:
df['date'] = df['ts'] // 86400000
# df = df.loc[(df['deny']!= True) & (df['dwell_time'] > 0)]
# df = df.loc[(df['dwell_time'] > 0)]
df['date_device_id'] = df.date.map(str) + "_" + df.device_id
df.head(5)

,area,deny,device_id,dwell_time,key,revisit_count,revisit_period,ts,date,date_device_id
0,1f-left,NaN,5d9884b5f69ed4381f64636502fbb49b,0,786:7fea86b665bf7e15:1f-left,NaN,NaN,1475666879496,17079,17079_5d9884b5f69ed4381f64636502fbb49b
1,out,NaN,a005a99c320acabaed202e97af035d60,38,786:7fea86b66628ee73:out,NaN,NaN,1475666877809,17079,17079_a005a99c320acabaed202e97af035d60
2,2f-left,NaN,47cbc1c26d0aa075de241967ac014e51,359,786:7fea86b667a38ff2:2f-left,NaN,NaN,1475666871751,17079,17079_47cbc1c26d0aa075de241967ac014e51
3,out,NaN,6e06ae972aa58dc4cec4612581c52ab5,46,786:7fea86b667e97cb2:out,NaN,NaN,1475666870632,17079,17079_6e06ae972aa58dc4cec4612581c52ab5
4,out,NaN,b336d82b169c78b3489aeb37abfdbbbb,13,786:7fea86b668984e6b:out,NaN,NaN,1475666867835,17079,17079_b336d82b169c78b3489aeb37abfdbbbb

In [13]:
# ### deny = 0은 걍 포함 (류인제씨 통화 이후)


# ### 직원 표시가 한번이라도 있는 device_id 삭제 (dwell_time > 0인 것들 중에서 직원 표시가 있는 id만 삭제. 
# ### dwell_time = 0인 로그가 왜이리 많은지.

# worker = set(df.loc[df['deny']==True]['device_id'].unique().tolist()) ### deny=True가 있는 user id의 set

# df = df[-df.device_id.isin(worker)] ### worker가 아닌 customer들만 df에서 남김.

In [12]:
df.groupby(['date_device_id'])['area']

In [15]:
## out만 있는 로그 제거 (일단 보류)

traj = df.groupby(['date_device_id'])['area']
ar = ['out']
temp = traj.unique()
temp2 = temp[-temp.apply(lambda x: (x == ar).all())]
df_sample = df[df.date_device_id.isin(temp2.index.tolist())]

In [16]:
mplogs = df_sample.sort_index(ascending=False).groupby('date_device_id', sort=False).apply(lambda x: x.index.tolist()).sort_index()

In [17]:
mpframe = mplogs.to_frame(name='logs').reset_index()

In [18]:
def finddata(logs, df, data):   # x is a list of logs
   return df.ix[logs][data].tolist()

In [19]:
mpframe['traj'] = mpframe['logs'].apply(lambda x: finddata(x, df, 'area'))
mpframe['deny'] = mpframe['logs'].apply(lambda x: finddata(x, df, 'deny'))

In [22]:
mpframe['ts_area'] = mpframe['logs'].apply(lambda x: finddata(x, df, 'ts'))
mpframe['dwelltime_area'] = mpframe['logs'].apply(lambda x: finddata(x, df, 'dwell_time'))

In [23]:
mpframe['ts_area'] = mpframe['ts_area'].apply(lambda x: [int(y/1000) for y in x])

In [24]:
mpframe.shape

(1649, 6)

In [25]:
mpframe.ts_area.head(5)

0     [1475234547, 1475235597, 1475235783, 1475235783]
1     [1475202371, 1475203382, 1475206174, 1475206226]
2    [1475206621, 1475206634, 1475206634, 147521073...
3    [1475203472, 1475203575, 1475203575, 147520357...
4                 [1475234943, 1475235584, 1475235584]
Name: ts_area, dtype: object

In [26]:
mpframe['hour_start'] = mpframe['ts_area'].apply(lambda x: [int(datetime.datetime.fromtimestamp(y).strftime('%H')) for y in x])
mpframe['time_start'] = mpframe['ts_area'].apply(lambda x: [datetime.datetime.fromtimestamp(y).strftime('%H:%M:%S') for y in x])  # %Y-%m-%d

In [27]:
mpframe.tail(1)

,date_device_id,logs,traj,deny,ts_area,dwelltime_area,hour_start,time_start
1648,17079_fe973d80374668c414ff2f5a9839249d,"[5803, 5802]","[out, in]","[nan, nan]","[1475645232, 1475645232]","[72, 0]","[14, 14]","[14:27:12, 14:27:12]"

In [28]:
def calend(x, y):
    return list(map(lambda i, j: i+j, x, y ))

In [29]:
mpframe['ts_area_end'] = mpframe[['ts_area', 'dwelltime_area']].apply(lambda x: calend(*x), axis=1)

In [30]:
mpframe['hour_end'] = mpframe['ts_area_end'].apply(lambda x: [int(datetime.datetime.fromtimestamp(y).strftime('%H')) for y in x])
mpframe['time_end'] = mpframe['ts_area_end'].apply(lambda x: [datetime.datetime.fromtimestamp(y).strftime('%H:%M:%S') for y in x])

In [31]:
def printall(mp, i, columnss):
    for column in columnss:
        print(mp[column].ix[i])

In [32]:
printall(mpframe, 2, ['traj', 'ts_area','ts_area_end'])

['out', 'in', '2f', 'out', 'out']
[1475206621, 1475206634, 1475206634, 1475210734, 1475228267]
[1475206687, 1475206634, 1475206634, 1475210805, 1475228324]

In [33]:
mpframe.to_pickle("../data/786_161005_sample/786_161005_sample_mpframe_161005.p")

In [34]:
mpframe = pd.read_pickle("../data/786_161005_sample/786_161005_sample_mpframe_161005.p")
mpframe.tail(5)   ### Show raw data

,date_device_id,logs,traj,deny,ts_area,dwelltime_area,hour_start,time_start,ts_area_end,hour_end,time_end
1644,17079_fb99d48afaa62a7c185003e67cd5455c,"[7721, 7707, 7706, 7692, 7689]","[out, in, 1f, 1f-right, 1f-left]","[nan, nan, nan, nan, nan]","[1475637112, 1475637160, 1475637160, 147563725...","[239, 98, 98, 2, 0]","[12, 12, 12, 12, 12]","[12:11:52, 12:12:40, 12:12:40, 12:14:16, 12:14...","[1475637351, 1475637258, 1475637258, 147563725...","[12, 12, 12, 12, 12]","[12:15:51, 12:14:18, 12:14:18, 12:14:18, 12:14..."
1645,17079_fbe5c9288d355da066ff664a33ee1585,"[6888, 6203, 6200, 6199, 6010, 6009, 5990, 597...","[out, out, in, 1f, 2f-inner, 2f, 1f, 1f-right,...","[nan, nan, nan, nan, nan, nan, nan, nan, nan]","[1475640826, 1475643526, 1475643543, 147564354...","[0, 1368, 1352, 0, 0, 0, 390, 233, 29]","[13, 13, 13, 13, 14, 14, 14, 14, 14]","[13:13:46, 13:58:46, 13:59:03, 13:59:03, 14:13...","[1475640826, 1475644894, 1475644895, 147564354...","[13, 14, 14, 13, 14, 14, 14, 14, 14]","[13:13:46, 14:21:34, 14:21:35, 13:59:03, 14:13..."
1646,17079_fbecca7be528454040eddc38511fb237,"[372, 371]","[out, in]","[nan, nan]","[1475665342, 1475665343]","[0, 0]","[20, 20]","[20:02:22, 20:02:23]","[1475665342, 1475665343]","[20, 20]","[20:02:22, 20:02:23]"
1647,17079_fc7ee36aa0b6e74ff5b5eb011214338a,"[7493, 7311, 7310, 7308]","[out, in, 2f, 1f]","[nan, nan, nan, nan]","[1475638142, 1475638917, 1475638917, 1475638926]","[795, 11, 0, 0]","[12, 12, 12, 12]","[12:29:02, 12:41:57, 12:41:57, 12:42:06]","[1475638937, 1475638928, 1475638917, 1475638926]","[12, 12, 12, 12]","[12:42:17, 12:42:08, 12:41:57, 12:42:06]"
1648,17079_fe973d80374668c414ff2f5a9839249d,"[5803, 5802]","[out, in]","[nan, nan]","[1475645232, 1475645232]","[72, 0]","[14, 14]","[14:27:12, 14:27:12]","[1475645304, 1475645232]","[14, 14]","[14:28:24, 14:27:12]"

In [35]:
mpframe = mpframe.loc[mpframe.date_device_id.str.startswith('17079')]  ## 10월 6일 데이터  - 이미 df에서 처리함.

In [36]:
mpframe

,date_device_id,logs,traj,deny,ts_area,dwelltime_area,hour_start,time_start,ts_area_end,hour_end,time_end
1400,17079_00164305a69029a80ad179a0027471b6,"[648, 536, 535, 533]","[out, in, 2f, 2f-left]","[nan, nan, nan, nan]","[1475664285, 1475664627, 1475664627, 1475664629]","[492, 0, 0, 0]","[19, 19, 19, 19]","[19:44:45, 19:50:27, 19:50:27, 19:50:29]","[1475664777, 1475664627, 1475664627, 1475664629]","[19, 19, 19, 19]","[19:52:57, 19:50:27, 19:50:27, 19:50:29]"
1401,17079_00b47d1e6f99510a0262d72d0a894188,"[295, 294]","[out, in]","[nan, nan]","[1475665581, 1475665581]","[0, 0]","[20, 20]","[20:06:21, 20:06:21]","[1475665581, 1475665581]","[20, 20]","[20:06:21, 20:06:21]"
1402,17079_02523fb4e3891e8d842bd9be817338e1,"[7586, 7510, 7323, 5973]","[out, in, out, out]","[nan, nan, nan, nan]","[1475637710, 1475638041, 1475638859, 1475644561]","[370, 0, 72, 0]","[12, 12, 12, 14]","[12:21:50, 12:27:21, 12:40:59, 14:16:01]","[1475638080, 1475638041, 1475638931, 1475644561]","[12, 12, 12, 14]","[12:28:00, 12:27:21, 12:42:11, 14:16:01]"
1403,17079_05b1975723c8fb27743eaf639990e643,"[9715, 9692, 9691]","[out, in, 1f]","[nan, nan, nan]","[1475626569, 1475626669, 1475626669]","[482, 0, 0]","[9, 9, 9]","[09:16:09, 09:17:49, 09:17:49]","[1475627051, 1475626669, 1475626669]","[9, 9, 9]","[09:24:11, 09:17:49, 09:17:49]"
1404,17079_0732a77684ac2d41636b1a80dc15eba5,"[2054, 2050, 2049, 1553]","[out, in, 1f, out]","[nan, nan, nan, nan]","[1475659176, 1475659197, 1475659197, 1475660834]","[37, 0, 0, 118]","[18, 18, 18, 18]","[18:19:36, 18:19:57, 18:19:57, 18:47:14]","[1475659213, 1475659197, 1475659197, 1475660952]","[18, 18, 18, 18]","[18:20:13, 18:19:57, 18:19:57, 18:49:12]"
1405,17079_07da6083ebf7ad93d8b4de155555b1c2,"[3023, 3009, 3008, 2943]","[out, in, 2f, 1f]","[nan, nan, nan, nan]","[1475655553, 1475655661, 1475655661, 1475655870]","[399, 291, 0, 0]","[17, 17, 17, 17]","[17:19:13, 17:21:01, 17:21:01, 17:24:30]","[1475655952, 1475655952, 1475655661, 1475655870]","[17, 17, 17, 17]","[17:25:52, 17:25:52, 17:21:01, 17:24:30]"
1406,17079_084effb5ee94cb576168adfc69d59fef,"[5880, 5843, 5842, 5815]","[out, in, 2f, 2f-left]","[nan, nan, nan, nan]","[1475644941, 1475645062, 1475645062, 1475645182]","[549, 120, 120, 0]","[14, 14, 14, 14]","[14:22:21, 14:24:22, 14:24:22, 14:26:22]","[1475645490, 1475645182, 1475645182, 1475645182]","[14, 14, 14, 14]","[14:31:30, 14:26:22, 14:26:22, 14:26:22]"
1407,17079_0966e98a3290f0b4535a0199774a5772,"[2565, 2548, 2547]","[out, in, 1f]","[nan, nan, nan]","[1475657479, 1475657540, 1475657540]","[121, 0, 0]","[17, 17, 17]","[17:51:19, 17:52:20, 17:52:20]","[1475657600, 1475657540, 1475657540]","[17, 17, 17]","[17:53:20, 17:52:20, 17:52:20]"
1408,17079_0a78b961558948e0d259e0b26cbd7176,"[3903, 3902, 1187, 1186]","[in, 1f, in, 1f]","[True, True, nan, nan]","[1475652242, 1475652242, 1475662083, 1475662083]","[0, 0, 0, 0]","[16, 16, 19, 19]","[16:24:02, 16:24:02, 19:08:03, 19:08:03]","[1475652242, 1475652242, 1475662083, 1475662083]","[16, 16, 19, 19]","[16:24:02, 16:24:02, 19:08:03, 19:08:03]"
1409,17079_0c93abc97c4deb4eada79fbb7a1466b2,"[7441, 7433, 7432, 1579]","[out, in, 1f, out]","[nan, nan, nan, nan]","[1475638315, 1475638341, 1475638341, 1475660766]","[228, 0, 0, 0]","[12, 12, 12, 18]","[12:31:55, 12:32:21, 12:32:21, 18:46:06]","[1475638543, 1475638341, 1475638341, 1475660766]","[12, 12, 12, 18]","[12:35:43, 12:32:21, 12:32:21, 18:46:06]"
1410,17079_0cae2e05922587e778e3c41efaba4591,"[5566, 5564, 5563, 5562]","[out, in, 1f-inner, 1f]","[nan, nan, nan, nan]","[1475646290, 1475646293, 1475646293, 1475646293]","[27, 0, 0, 0]","[14, 14, 14, 14]","[14:44:50, 14:44:53, 14:44:53, 14:44:53]","[1475646317, 1475646293, 1475646293, 1475646293]","[14, 14, 14, 14]","[14:45:17, 14:44:53, 14:44:53, 14:44:53]"
1411,17079_0d40eef6aed0f05622349f05d8d1c960,"[4853, 4847, 4846]","[out, in, 1f]","[nan, nan, nan]","[1475649060, 1475649081, 1475649081]","[80, 0, 0]","[15, 15, 15]","[15:31:00, 15:31:21, 15:31:21]","[1475649140, 1475649081, 1475649081]","[15, 15, 15]","[15:32:20, 15:31:21, 15:31:21]"
1412,17079_10498d7b8456645f44a800450622b15f,"[1762, 1757, 1756]","[out, in, 1f]","[nan, nan, nan]","[1475660173, 1475660184, 1475660184]","[41, 0, 0]","[18, 18, 18]","[18:36:13, 18:36:24, 18:36:24]","[1475660214, 1475660184, 1475660184]","[18, 18, 18]","[18:36:54, 18:36:24, 18:36:24]"
1413,17079_10dbcb7afb0fcda333dc8b7aaccd7f4b,"[8925, 8614, 4242, 4233, 4232, 4231]","[out, out, out, in, 1f-right, 1f]","[nan, nan, nan, nan, nan, nan]","[1475631068, 1475632983, 1475651209, 147565123...","[4, 159, 329, 0, 0, 0]","[10, 11, 16, 16, 16, 16]","[10:31:08, 11:03:03, 16:06:49, 16:07:10, 16:07...","[1475631072, 1475633142, 1475651538, 147565123...","[10, 11, 16, 16, 16, 16]","[10:31:12, 11:05:42, 16:12:18, 16:07:10, 16:07..."
1414,17079_130ba2464a97682f69fe8f124bde55d4,"[3233, 3229, 3228]","[out, in, 1f]","[nan, nan, nan]","[1475654742, 1475654749, 1475654749]","[7, 0, 0]","[17, 17, 17]","[17:05:42, 17:05:49, 17:05:49]","[1475654749, 1475654749, 1475654749]","[17, 17, 17]","[17:05:49, 17:05:49, 17:05:49]"
1415,17079_1553fef72bbfa3c06809396ddb3510b2,"[6660, 6651]","[out, in]","[nan, nan]","[1475641882, 1475641905]","[34, 0]","[13, 13]","[13:31:22, 13:31:45]","[1475641916, 1475641905]","[13, 13]","[13:31:56, 13:31:45]"
1416,17079_15677e389799771d05567ba83856f954,"[1366, 716, 699]","[out, out, in]","[nan, nan, nan]","[1475661455, 1475663962, 1475664047]","[63, 98, 0]","[18, 19, 19]","[18:57:35, 19:39:22, 19:40:47]","[1475661518, 1475664060, 1475664047]","[18, 19, 19]","[18:58:38, 19:41:00, 19:40:47]"
1417,17079_1794a9242e65d70486fad81614f00c40,"[9687, 8820, 7642, 7641, 7640, 5241, 3746, 1092]","[out, out, out, in, 2f, out, out, out]","[True, True, True, True, True, True, True, nan]","[1475626691, 1475631725, 1475637477, 147563747...","[6, 6, 0, 0, 0, 0, 6, 0]","[9, 10, 12, 12, 12, 15, 16, 19]","[09:18:11, 10:42:05, 12:17:57, 12:17:57, 12:17...","[1475626697, 1475631731, 1475637477, 147563747...","[9, 10, 12, 12, 12, 15, 16, 19]","[09:18:17, 10:42:11, 12:17:57, 12:17:57, 12:17..."
1418,17079_196705fe159f5b7806e864e85f1b5306,"[3538, 3530, 3529]","[out, in, 1f]","[nan, nan, nan]","[1475653468, 1475653498, 1475653498]","[76, 0, 0]","[16, 16, 16]","[16:44:28, 16:44:58, 16:44:58]","[1475653544, 1475653498, 1475653498]","[16, 16, 16]","[16:45:44, 16:44:58, 16:44:58]"
1419,17079_1968754b8bcf3d58895fd64ed717a422,"[9261, 7240, 6370, 2992, 2991, 2990]","[out, out, out, out, in, 1f]","[True, True, True, True, True, True]","[1475628955, 1475639254, 1475642914, 147565569...","[115, 0, 117, 0, 0, 0]","[9, 12, 13, 17, 17, 17]","[09:55:55, 12:47:34, 13:48:34, 17:21:38, 17:21...","[1475629070, 1475639254, 1475643031, 147565569...","[9, 12, 13, 17, 17, 17]","[09:57:50, 12:47:34, 13:50:31, 17:21:38, 17:21..."
1420,17079_19e0d79dbc42776cf28f55db4ffbf859,"[841, 422, 408, 407]","[out, out, in, 1f]","[nan, nan, nan, nan]","[1475663466, 1475665191, 1475665226, 1475665226]","[0, 45, 0, 0]","[19, 19, 20, 20]","[19:31:06, 19:59:51, 20:00:26, 20:00:26]","[1475663466, 1475665236, 1475665226, 1475665226]","[19, 20, 20, 20]","[19:31:06, 20:00:36, 20:00:26, 20:00:26]"
1421,17079_19f93d1392e335229388d141f383c615,"[823, 784, 782]","[out, in, 2f]","[nan, nan, nan]","[1475663533, 1475663677, 1475663697]","[177, 20, 0]","[19, 19, 19]","[19:32:13, 19:34:37, 19:34:57]","[1475663710, 1475663697, 1475663697]","[19, 19, 19]","[19:35:10, 19:34:57, 19:34:57]"
1422,17079_1a632bd655d5615254860e693836c366,"[8457, 8220, 8203, 8202]","[out, out, in, 1f]","[nan, nan, nan, nan]","[1475633767, 1475635003, 1475635067, 1475635067]","[203, 1264, 0, 0]","[11, 11, 11, 11]","[11:16:07, 11:36:43, 11:37:47, 11:37:47]","[1475633970, 1475636267, 1475635067, 1475635067]","[11, 11, 11, 11]","[11:19:30, 11:57:47, 11:37:47, 11:37:47]"
1423,17079_1afa8b9de659f7c10db17ab7e63e1a7f,"[6910, 6909, 6908, 3133]","[out, in, 1f, out]","[nan, nan, nan, nan]","[1475640749, 1475640750, 1475640750, 1475655121]","[5, 0, 0, 37]","[13, 13, 13, 17]","[13:12:29, 13:12:30, 13:12:30, 17:12:01]","[1475640754, 1475640750, 1475640750, 1475655158]","[13, 13, 13, 17]","[13:12:34, 13:12:30, 13:12:30, 17:12:38]"
1424,17079_1bf0fed653ec2f7c50ea9609724947ba,"[5324, 4990, 4950, 4949]","[out, out, in, 1f]","[nan, nan, nan, nan]","[1475647241, 1475648599, 1475648702, 1475648702]","[66, 125, 0, 0]","[15, 15, 15, 15]","[15:00:41, 15:23:19, 15:25:02, 15:25:02]","[1475647307, 1475648724, 1475648702, 1475648702]","[15, 15, 15, 15]","[15:01:47, 15:25:24, 15:25:02, 15:25:02]"
1425,17079_1c1a91a753994947091dcd775fb21577,"[9806, 6654, 6631, 6630, 6629]","[out, out, in, 1f-right, 1f]","[nan, nan, nan, nan, nan]","[1475626169, 1475641894, 1475641965, 147564196...","[762, 257, 0, 0, 0]","[9, 13, 13, 13, 13]","[09:09:29, 13:31:34, 13:32:45, 13:32:45, 13:32...","[1475626931, 1475642151, 1475641965, 147564196...","[9, 13, 13, 13, 13]","[09:22:11, 13:35:51, 13:32:45, 13:32:45, 13:32..."
1426,17079_1d1ea784db750b8637d2c8c5f78f5844,"[7884, 6939, 6936, 6935, 6934]","[out, out, in, 1f-inner, 1f]","[nan, nan, nan, nan, nan]","[1475636443, 1475640658, 1475640662, 147564066...","[14, 60, 0, 0, 0]","[12, 13, 13, 13, 13]","[12:00:43, 13:10:58, 13:11:02, 13:11:02, 13:11...","[1475636457, 1475640718, 1475640662, 147564066...","[12, 13, 13, 13, 13]","[12:00:57, 13:11:58, 13:11:02, 13:11:02, 13:11..."
1427,17079_1d40204248135135d3197102868efd71,"[7993, 7090, 5456, 4076, 2915, 2435, 2426, 1282]","[out, out, out, out, out, out, in, out]","[True, True, True, True, True, True, True, True]","[1475636076, 1475639920, 1475646706, 147565171...","[13, 6, 13, 12, 0, 13, 0, 0]","[11, 12, 14, 16, 17, 18, 18, 19]","[11:54:36, 12:58:40, 14:51:46, 16:15:16, 17:26...","[1475636089, 1475639926, 1475646719, 147565172...","[11, 12, 14, 16, 17, 18, 18, 19]","[11:54:49, 12:58:46, 14:51:59, 16:15:28, 17:26..."
1428,17079_1eeb3926bccb98540959337bbe3d6c18,"[5476, 5075, 5074]","[out, out, in]","[nan, nan, nan]","[1475646652, 1475648204, 1475648208]","[87, 493, 0]","[14, 15, 15]","[14:50:52, 15:16:44, 15:16:48]","[1475646739, 1475648697, 1475648208]","[14, 15, 15]","[14:52:19, 15:24:57, 15:16:48]"
1429,17079_21b8dad5dfa1929481c96edac3bc4221,"[5939, 5785, 5784]","[out, in, 1f]","[nan, nan, nan]","[1475644702, 1475645310, 1475645310]","[1990, 0, 0]","[14, 14, 14]","[14:18:22, 14:28:30, 14:28:30]","[1475646692, 1475645310, 1475645310]","[14, 14, 14]","[14:51:32, 14:28:30, 14:28:30]"
...,...,...,...,...,...,...,...,...,...,...,...
1619,17079_e16b513cee477a2112c6b65e10135d15,"[346, 324, 323]","[out, in, 2f]","[nan, nan, nan]","[1475665411, 1475665474, 1475665474]","[145, 0, 0]","[20, 20, 20]","[20:03:31, 20:04:34, 20:04:34]","[1475665556, 1475665474, 1475665474]","[20, 20, 20]","[20:05:56, 20:04:34, 20:04:34]"
1620,17079_e1e8f5862bca89d8c6c0a3f4b56dbe7f,"[5064, 2504, 2485, 2484]","[out, out, in, 1f]","[nan, nan, nan, nan]","[1475648241, 1475657789, 1475657857, 1475657857]","[0, 73, 0, 0]","[15, 17, 17, 17]","[15:17:21, 17:56:29, 17:57:37, 17:57:37]","[1475648241, 1475657862, 1475657857, 1475657857]","[15, 17, 17, 17]","[15:17:21, 17:57:42, 17:57:37, 17:57:37]"
1621,17079_e325a4cab9085b75c51aa67f8057c4a5,"[6459, 6456, 6455, 6454, 5453]","[out, in, 1f-right, 1f, out]","[nan, nan, nan, nan, nan]","[1475642620, 1475642627, 1475642627, 147564262...","[47, 2, 0, 2, 146]","[13, 13, 13, 13, 14]","[13:43:40, 13:43:47, 13:43:47, 13:43:47, 14:51...","[1475642667, 1475642629, 1475642627, 147564262...","[13, 13, 13, 13, 14]","[13:44:27, 13:43:49, 13:43:47, 13:43:49, 14:54..."
1622,17079_e3a6309e8d18d66a1a7b56bd01c90677,"[6571, 1771, 1768, 1767]","[out, out, in, 1f]","[nan, nan, nan, nan]","[1475642178, 1475660110, 1475660132, 1475660132]","[0, 95, 0, 0]","[13, 18, 18, 18]","[13:36:18, 18:35:10, 18:35:32, 18:35:32]","[1475642178, 1475660205, 1475660132, 1475660132]","[13, 18, 18, 18]","[13:36:18, 18:36:45, 18:35:32, 18:35:32]"
1623,17079_e3e03bc094aef00d84410ec8ff9b8625,"[7934, 7927, 7926, 7925, 7905, 7904, 7667]","[out, in, 1f, 1f-right, 2f, 2f-inner, out]","[nan, nan, nan, nan, nan, nan, nan]","[1475636307, 1475636345, 1475636345, 147563634...","[318, 46, 46, 0, 0, 0, 18]","[11, 11, 11, 11, 11, 11, 12]","[11:58:27, 11:59:05, 11:59:05, 11:59:06, 11:59...","[1475636625, 1475636391, 1475636391, 147563634...","[12, 11, 11, 11, 11, 11, 12]","[12:03:45, 11:59:51, 11:59:51, 11:59:06, 11:59..."
1624,17079_e3f308ebd4d7eae5fd698a3f09477cfe,"[336, 335, 334, 333]","[out, in, 2f, 2f-right]","[nan, nan, nan, nan]","[1475665445, 1475665445, 1475665445, 1475665446]","[0, 0, 0, 0]","[20, 20, 20, 20]","[20:04:05, 20:04:05, 20:04:05, 20:04:06]","[1475665445, 1475665445, 1475665445, 1475665446]","[20, 20, 20, 20]","[20:04:05, 20:04:05, 20:04:05, 20:04:06]"
1625,17079_e5ceea2fc64866e6a96fe2d0de040c3e,"[3673, 3644, 3643]","[out, in, 1f]","[nan, nan, nan]","[1475652998, 1475653124, 1475653124]","[232, 0, 0]","[16, 16, 16]","[16:36:38, 16:38:44, 16:38:44]","[1475653230, 1475653124, 1475653124]","[16, 16, 16]","[16:40:30, 16:38:44, 16:38:44]"
1626,17079_e6069fd7e0e7b7d0499f051dd98f4c67,"[3416, 3411, 3410]","[out, in, 1f]","[nan, nan, nan]","[1475653922, 1475653934, 1475653934]","[24, 0, 0]","[16, 16, 16]","[16:52:02, 16:52:14, 16:52:14]","[1475653946, 1475653934, 1475653934]","[16, 16, 16]","[16:52:26, 16:52:14, 16:52:14]"
1627,17079_e68eeadbc8f2baa477126f32d7f72800,"[7557, 7556, 7555]","[out, in, 2f]","[nan, nan, nan]","[1475637845, 1475637845, 1475637845]","[53, 0, 0]","[12, 12, 12]","[12:24:05, 12:24:05, 12:24:05]","[1475637898, 1475637845, 1475637845]","[12, 12, 12]","[12:24:58, 12:24:05, 12:24:05]"
1628,17079_e91df0c7d652d46088e33d82f9ee4709,"[7227, 7226, 7225, 7224, 1276]","[out, in, 1f-right, 1f, out]","[nan, nan, nan, nan, nan]","[1475639322, 1475639322, 1475639322, 147563932...","[0, 0, 0, 0, 0]","[12, 12, 12, 12, 19]","[12:48:42, 12:48:42, 12:48:42, 12:48:42, 19:01...","[1475639322, 1475639322, 1475639322, 147563932...","[12, 12, 12, 12, 19]","[12:48:42, 12:48:42, 12:48:42, 12:48:42, 19:01..."
1629,17079_e92bcd8eafcc6bf210591eabb795d837,"[6979, 6978, 6977, 6976]","[out, in, 2f, 2f-right]","[nan, nan, nan, nan]","[1475640477, 1475640477, 1475640477, 1475640477]","[0, 0, 0, 0]","[13, 13, 13, 13]","[13:07:57, 13:07:57, 13:07:57, 13:07:57]","[1475640477, 1475640477, 1475640477, 1475640477]","[13, 13, 13, 13]","[13:07:57, 13:07:57, 13:07:57, 13:07:57]"
1630,17079_eb048e9ee26ef2eb5549e46c4df16d24,"[6001, 5993, 5992]","[out, in, 1f]","[nan, nan, nan]","[1475644448, 1475644486, 1475644486]","[69, 0, 0]","[14, 14, 14]","[14:14:08, 14:14:46, 14:14:46]","[1475644517, 1475644486, 1475644486]","[14, 14, 14]","[14:15:17, 14:14:46, 14:14:46]"
1631,17079_ec588edbcb0b6975125e3c441a389381,"[8778, 8573, 8389, 8335, 8143, 7867, 7865, 786...","[out, in, 3f, 1f, 1f-right, out, in, 1f, 1f-ri...","[True, True, True, True, True, True, True, Tru...","[1475632108, 1475633222, 1475634036, 147563439...","[3692, 2577, 0, 1404, 406, 651, 650, 650, 0, 1...","[10, 11, 11, 11, 11, 12, 12, 12, 12, 12, 12, 1...","[10:48:28, 11:07:02, 11:20:36, 11:26:36, 11:43...","[1475635800, 1475635799, 1475634036, 147563580...","[11, 11, 11, 11, 11, 12, 12, 12, 12, 13, 12, 1...","[11:50:00, 11:49:59, 11:20:36, 11:50:00, 11:50..."
1632,17079_ee52f271208d976b40e60a256218a8f5,"[3492, 1851, 1839, 1838]","[out, out, in, 1f]","[nan, nan, nan, nan]","[1475653631, 1475659806, 1475659825, 1475659825]","[27, 47, 0, 0]","[16, 18, 18, 18]","[16:47:11, 18:30:06, 18:30:25, 18:30:25]","[1475653658, 1475659853, 1475659825, 1475659825]","[16, 18, 18, 18]","[16:47:38, 18:30:53, 18:30:25, 18:30:25]"
1633,17079_eff356ec68a573d7fd55a426b09af4f7,"[7222, 7215, 7214]","[out, in, 1f]","[nan, nan, nan]","[1475639323, 1475639343, 1475639343]","[622, 0, 0]","[12, 12, 12]","[12:48:43, 12:49:03, 12:49:03]","[1475639945, 1475639343, 1475639343]","[12, 12, 12]","[12:59:05, 12:49:03, 12:49:03]"
1634,17079_f1bbb036aa43c399f4eb722cdd23db38,"[8691, 8690, 8689, 8688, 8509, 8117, 8116, 811...","[out, in, 1f-right, 1f, 1f-inner, in, 1f-inner...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[1475632538, 1475632539, 1475632539, 147563253...","[4227, 1758, 759, 1241, 0, 0, 0, 0, 0, 0]","[10, 10, 10, 10, 11, 11, 11, 11, 12, 12]","[10:55:38, 10:55:39, 10:55:39, 10:55:39, 11:11...","[1475636765, 1475634297, 1475633298, 147563378...","[12, 11, 11, 11, 11, 11, 11, 11, 12, 12]","[12:06:05, 11:24:57, 11:08:18, 11:16:20, 11:11..."
1635,17079_f3e152d0ad2faa91206b69db90d6284b,"[7537, 7332, 7331, 7330, 6666, 6460, 5732, 573...","[out, in, 1f-right, 1f, 1f-right, 1f-right, in...","[True, True, True, True, True, True, True, Tru...","[1475637910, 1475638817, 1475638817, 147563881...","[27606, 4867, 1736, 4867, 0, 0, 1465, 1465, 79...","[12, 12, 12, 12, 13, 13, 14, 14, 15, 15, 15, 1...","[12:25:10, 12:40:17, 12:40:17, 12:40:17, 13:31...","[1475665516, 1475643684, 1475640553, 147564368...","[20, 14, 13, 14, 13, 13, 14, 14, 17, 17, 15, 1...","[20:05:16, 14:01:24, 13:09:13, 14:01:24, 13:31..."
1636,17079_f42776d98f7a105dac4fff35051ebcc8,"[7089, 7088, 7087, 7086]","[out, in, 1f, 1f-right]","[nan, nan, nan, nan]","[1475639927, 1475639927, 1475639927, 1475639927]","[109, 0, 0, 0]","[12, 12, 12, 12]","[12:58:47, 12:58:47, 12:58:47, 12:58:47]","[1475640036, 1475639927, 1475639927, 1475639927]","[13, 12, 12, 12]","[13:00:36, 12:58:47, 12:58:47, 12:58:47]"
1637,17079_f4bdffa5f9f857b0dc5c2b9a74e0a362,"[387, 386, 385, 384]","[out, in, 2f-right, 2f]","[nan, nan, nan, nan]","[1475665304, 1475665304, 1475665304, 1475665304]","[0, 0, 0, 0]","[20, 20, 20, 20]","[20:01:44, 20:01:44, 20:01:44, 20:01:44]","[1475665304, 1475665304, 1475665304, 1475665304]","[20, 20, 20, 20]","[20:01:44, 20:01:44, 20:01:44, 20:01:44]"
1638,17079_f569365daf218d12d4f4b2f2b2443564,"[5848, 5742, 5741, 5740]","[out, in, 1f-inner, 1f]","[nan, nan, nan, nan]","[1475645052, 1475645474, 1475645474, 1475645474]","[453, 0, 0, 0]","[14, 14, 14, 14]","[14:24:12, 14:31:14, 14:31:14, 14:31:14]","[1475645505, 1475645474, 1475645474, 1475645474]","[14, 14, 14, 14]","[14:31:45, 14:31:14, 14:31:14, 14:31:14]"
1639,17079_f5f1f5ea11ec730c3c6aca64860a4292,"[3587, 3480, 3479, 3472]","[out, in, 1f, 1f-inner]","[nan, nan, nan, nan]","[1475653302, 1475653684, 1475653687, 1475653724]","[488, 51, 47, 0]","[16, 16, 16, 16]","[16:41:42, 16:48:04, 16:48:07, 16:48:44]","[1475653790, 1475653735, 1475653734, 1475653724]","[16, 16, 16, 16]","[16:49:50, 16:48:55, 16:48:54, 16:48:44]"
1640,17079_f682b75d2bf0d345aca53d851f2e5746,"[8898, 7482, 7478, 7300, 6740, 6087, 5286, 507...","[out, out, in, out, out, out, out, out, out, o...","[True, True, True, True, True, True, True, Tru...","[1475631210, 1475638193, 1475638206, 147563895...","[0, 13, 0, 0, 672, 0, 0, 0, 0, 0, 0, 43]","[10, 12, 12, 12, 13, 14, 15, 15, 17, 18, 19, 20]","[10:33:30, 12:29:53, 12:30:06, 12:42:30, 13:25...","[1475631210, 1475638206, 1475638206, 147563895...","[10, 12, 12, 12, 13, 14, 15, 15, 17, 18, 19, 20]","[10:33:30, 12:30:06, 12:30:06, 12:42:30, 13:36..."
1641,17079_f7d89fef0d71bcf278eff7487896a964,"[6279, 5576, 5395, 5394, 4998]","[out, out, in, 1f, out]","[nan, nan, nan, nan, nan]","[1475643237, 1475646242, 1475647018, 147564701...","[1631, 908, 0, 0, 0]","[13, 14, 14, 14, 15]","[13:53:57, 14:44:02, 14:56:58, 14:56:58, 15:23...","[1475644868, 1475647150, 1475647018, 147564701...","[14, 14, 14, 14, 15]","[14:21:08, 14:59:10, 14:56:58, 14:56:58, 15:23..."
1642,17079_fad79d8d0ad9a3a21be62cb13f663b28,"[4599, 4593, 4592]","[out, in, 1f]","[nan, nan, nan]","[1475649965, 1475649984, 1475649984]","[57, 0, 0]","[15, 15, 15]","[15:46:05, 15:46:24, 15:46:24]","[1475650022, 1475649984, 1475649984]","[15, 15, 15]","[15:47:02, 15:46:24, 15:46:24]"
1643,17079_fb473d7b251714e84daf7dbb4139925e,"[1626, 1594, 1593, 1592]","[out, in, 1f-inner, 1f]","[nan, nan, nan, nan]","[1475660632, 1475660731, 1475660731, 1475660731]","[132, 0, 0, 0]","[18, 18, 18, 18]","[18:43:52, 18:45:31, 18:45:31, 18:45:31]","[1475660764, 1475660731, 1475660731, 1475660731]","[18, 18, 18, 18]","[18:46:04, 18:45:31, 18:45:31, 18:45:31]"

In [78]:
stime = mpframe.hour_start.apply(lambda x: min(x))
etime = mpframe.hour_end.apply(lambda x: max(x))

In [96]:
stime2 = stime.loc[(stime == 10) | (stime == 11) | (stime == 12)]
etime2 = etime.loc[(etime == 11) | (etime == 12) | (etime == 13) | (etime == 14) | (etime == 15)]
time2 = list(set(stime2.index) & set(etime2.index))

In [97]:
print(len(stime2))
print(len(etime2))
print(len(time2))

62
94
40

In [98]:
mpframe2 = mpframe.ix[time2]

In [206]:
def ganttprint(mfs, i):
    
    qa = mfs['traj'].ix[i] + [1000*y for y in mfs['ts_area'].ix[i]] + [1000*z for z in mfs['ts_area_end'].ix[i]]
    l = int(len(qa)/3)
    qb = np.asarray(qa)
    shape = ( 3,l )
    qc = qb.reshape( shape ).T
    qd = pd.DataFrame(qc, columns=['Task', 'Start', 'Finish'])
    qd['Start'] = qd['Start'].astype('int') 
    qd['Finish'] = qd['Finish'].astype('int')
    qd['Complete'] = np.arange(40, 60, (60-40)/l)
    qd['t_start'] = qd['Start'].apply(lambda x: datetime.datetime.fromtimestamp(x/1000).strftime('%H:%M:%S'))
    qd['t_end'] = qd['Finish'].apply(lambda x: datetime.datetime.fromtimestamp(x/1000).strftime('%H:%M:%S'))
    # .as_matrix()
    return qd

In [100]:
lenlogs = np.asarray([len(x) for x in mpframe2.logs])
indxx = np.argsort(lenlogs, )
largg = indxx[::-1]

In [207]:
ganttprint(mpframe2, time2[largg[5]])   #0, 1, 3, 4  (처음부터 켠거)   #5 (나중에 켠거)

       Task          Start         Finish  Complete   t_start     t_end
0       out  1475635248000  1475637243000      40.0  11:40:48  12:14:03
1        in  1475635270000  1475636545000      42.0  11:41:10  12:02:25
2        1f  1475635270000  1475636545000      44.0  11:41:10  12:02:25
3        2f  1475635291000  1475635477000      46.0  11:41:31  11:44:37
4        3f  1475635327000  1475635327000      48.0  11:42:07  11:42:07
5  1f-inner  1475635503000  1475635955000      50.0  11:45:03  11:52:35
6   1f-left  1475635895000  1475635925000      52.0  11:51:35  11:52:05
7        2f  1475636297000  1475636478000      54.0  11:58:17  12:01:18
8   2f-left  1475636297000  1475636297000      56.0  11:58:17  11:58:17
9  1f-right  1475636546000  1475636546000      58.0  12:02:26  12:02:26

In [137]:
def printchartlah(f, i):
    lenlogs = np.asarray([len(x) for x in f.logs])
    indxx = np.argsort(lenlogs, )
    largg = indxx[::-1]
    
    print("---------------", i,'th longest moving pattern: Sequence #', largg[i])
    print("---------------", "Date_Device_id: ", f[largg[i]:largg[i]+1].date_device_id.values[0])
    qd = ganttprint(f, mpframe2.index[largg][i])  ## .sort_index(ascending=False)
    print(qd[['Task','t_start', 't_end']])
    return qd

In [208]:
qd0 = printchartlah(mpframe2,5)

--------------- 5 th longest moving pattern: Sequence # 14
--------------- Date_Device_id:  17079_ae9b6354a59e14ce83d44c17ec9ee71a
       Task   t_start     t_end
0       out  11:40:48  12:14:03
1        in  11:41:10  12:02:25
2        1f  11:41:10  12:02:25
3        2f  11:41:31  11:44:37
4        3f  11:42:07  11:42:07
5  1f-inner  11:45:03  11:52:35
6   1f-left  11:51:35  11:52:05
7        2f  11:58:17  12:01:18
8   2f-left  11:58:17  11:58:17
9  1f-right  12:02:26  12:02:26

In [57]:
import plotly.plotly as py
from plotly.tools import FigureFactory as FF
import datetime

In [209]:
fig0 = FF.create_gantt(qd0[['Task','Start', 'Finish', 'Complete']], colors='Viridis', index_col='Complete', show_colorbar=True)
p0 = py.iplot(fig0, filename='Numeric Variable', world_readable=True)
p0

In [171]:
qd1 = printchartlah(mpframe_cand, 1)

--------------- 1 th longest moving pattern: Sequence # 1
--------------- Date_Device_id:  17071_5dd63ba8a12d13f0a397a548062be9c4
        Task   t_start     t_end
0        out  13:17:41  15:32:57
1         in  13:18:01  15:26:00
2         1f  13:18:01  13:18:04
3         2f  13:22:26  15:22:34
4   2f-inner  13:23:13  13:55:42
5         1f  13:36:42  13:41:27
6   1f-right  13:38:49  13:41:27
7    1f-left  13:38:49  13:41:26
8    2f-left  13:49:13  14:09:53
9         1f  14:14:42  14:30:41
10   2f-left  14:35:50  14:51:30
11        1f  15:06:58  15:22:34
12   2f-left  15:11:45  15:22:34
13  2f-right  15:17:19  15:22:30

In [172]:
fig1 = FF.create_gantt(qd1[['Task','Start', 'Finish', 'Complete']], colors='Viridis', index_col='Complete', show_colorbar=True)
p1 = py.iplot(fig1, filename='Numeric Variable', world_readable=True)
p1

In [173]:
qd2 = printchartlah(mpframe_cand, 2)

--------------- 2 th longest moving pattern: Sequence # 2
--------------- Date_Device_id:  17071_8c854c38fdb2f233eb6bc6c80df6c11e
       Task   t_start     t_end
0       out  13:14:06  15:34:41
1        in  13:14:06  15:34:40
2        1f  13:14:06  13:19:23
3        2f  13:14:07  15:14:14
4   2f-left  13:24:41  13:32:55
5        1f  13:38:13  13:54:04
6  2f-inner  14:17:24  14:27:58
7   2f-left  14:17:25  14:38:33
8   2f-left  15:03:28  15:08:41

In [174]:
fig2 = FF.create_gantt(qd2[['Task','Start', 'Finish', 'Complete']], colors='Viridis', index_col='Complete', show_colorbar=True)
p2 = py.iplot(fig2, filename='Numeric Variable', world_readable=True)
p2

In [175]:
qd3 = printchartlah(mpframe_cand, 3)

--------------- 3 th longest moving pattern: Sequence # 0
--------------- Date_Device_id:  17071_5550d077aac5ff2fdab5300565143d8c
       Task   t_start     t_end
0       out  13:13:32  15:32:50
1        in  13:14:31  13:45:49
2        2f  13:14:31  13:15:16
3        2f  13:35:35  13:45:49
4  1f-right  13:37:50  13:41:20
5        1f  13:37:50  13:41:20
6        in  14:01:20  14:30:05
7        2f  14:01:20  14:10:49
8        in  15:23:46  15:24:34

In [176]:
fig3 = FF.create_gantt(qd3[['Task','Start', 'Finish', 'Complete']], colors='Viridis', index_col='Complete', show_colorbar=True)
p3 = py.iplot(fig3, filename='Numeric Variable', world_readable=True)
p3

In [154]:
qd4 = printchartlah(mpframe_cand, 4)

--------------- 4 th longest moving pattern: Sequence # 4
--------------- Date_Device_id:  17071_de12dccd21897a9d433ecfef28afdf63
       Task   t_start     t_end
0       out  13:15:34  13:55:37
1        in  13:15:34  13:28:38
2        1f  13:15:34  13:28:38
3  1f-right  13:15:35  13:28:19
4        in  13:40:43  13:55:38
5        1f  13:46:03  13:55:37
6  1f-right  13:46:03  13:53:38

In [155]:
fig4 = FF.create_gantt(qd4[['Task','Start', 'Finish', 'Complete']], colors='Viridis', index_col='Complete', show_colorbar=True)
p4 = py.iplot(fig4, filename='Numeric Variable', world_readable=True)
p4

In [47]:
df['ts_start'] = df['ts'].apply(lambda x: datetime.datetime.fromtimestamp(x/1000).strftime('%Y-%m-%d %H:%M:%S'))
df2 = df.loc[df.area != 'out']

In [48]:
df

,area,deny,device_id,dwell_time,key,revisit_count,revisit_period,ts,date,date_device_id,ts_start
1,out,NaN,736652b63d4cff1ce9648fd19c195b1e,282,786:7fea89496fbc7c1c:out,NaN,NaN,1474975827000,17071,17071_736652b63d4cff1ce9648fd19c195b1e,2016-09-27 20:30:27
2,out,NaN,b14b0a69235292dd4d09f75f19079bed,38,786:7fea894970a96da6:out,NaN,NaN,1474975823209,17071,17071_b14b0a69235292dd4d09f75f19079bed,2016-09-27 20:30:23
3,out,NaN,b59aa37cc2e30b17c1a3617a442f2f78,39,786:7fea894970bdadfa:out,NaN,NaN,1474975822885,17071,17071_b59aa37cc2e30b17c1a3617a442f2f78,2016-09-27 20:30:22
4,out,NaN,4cfef2077e81acfb7e8ed5f266408f7e,14,786:7fea894971d33cf5:out,NaN,NaN,1474975818444,17071,17071_4cfef2077e81acfb7e8ed5f266408f7e,2016-09-27 20:30:18
8,out,NaN,54cdaa508cfe85aaa6a9f022d612ce23,3,786:7fea894974f2ae56:out,NaN,NaN,1474975805653,17071,17071_54cdaa508cfe85aaa6a9f022d612ce23,2016-09-27 20:30:05
12,out,NaN,075643e2e352d326d07dc655d7065600,4,786:7fea8949759fbf22:out,NaN,NaN,1474975802884,17071,17071_075643e2e352d326d07dc655d7065600,2016-09-27 20:30:02
14,out,NaN,37e306833014d73ba32dec95cfe4c95a,2,786:7fea894978509ec5:out,NaN,NaN,1474975791862,17071,17071_37e306833014d73ba32dec95cfe4c95a,2016-09-27 20:29:51
16,out,NaN,ad911d62a54e9b2ffc4727f0641a48ec,2,786:7fea894978680fa5:out,NaN,NaN,1474975791487,17071,17071_ad911d62a54e9b2ffc4727f0641a48ec,2016-09-27 20:29:51
18,out,NaN,e02bbec13ec5e0fde594790c95172cb5,3,786:7fea894979905e01:out,NaN,NaN,1474975786746,17071,17071_e02bbec13ec5e0fde594790c95172cb5,2016-09-27 20:29:46
24,out,NaN,080653b7f19a3c4cbfa49946d728c846,682,786:7fea894986bdfdc0:out,NaN,NaN,1474975732768,17071,17071_080653b7f19a3c4cbfa49946d728c846,2016-09-27 20:28:52
25,out,NaN,468c8a2555ebd119dc5fb743ba32804a,5,786:7fea894987477ff2:out,NaN,NaN,1474975730568,17071,17071_468c8a2555ebd119dc5fb743ba32804a,2016-09-27 20:28:50
30,out,NaN,2993d10020116662d96dcec50f61b6b1,3,786:7fea8949889e8d8a:out,NaN,NaN,1474975725079,17071,17071_2993d10020116662d96dcec50f61b6b1,2016-09-27 20:28:45
31,out,NaN,0a53f3d472007ba43e53ffe01650b951,16,786:7fea89498a46bfb3:out,NaN,NaN,1474975718292,17071,17071_0a53f3d472007ba43e53ffe01650b951,2016-09-27 20:28:38
36,out,NaN,86de14a9e1338347245f9cfea0e50cf4,40,786:7fea894993803dd2:out,NaN,NaN,1474975680508,17071,17071_86de14a9e1338347245f9cfea0e50cf4,2016-09-27 20:28:00
40,out,NaN,16a7de80f418d442448721b86d586e4e,23,786:7fea89499681be21:out,NaN,NaN,1474975668196,17071,17071_16a7de80f418d442448721b86d586e4e,2016-09-27 20:27:48
42,out,NaN,9e72b06c707cb4103ec1c4c5873b5812,580,786:7fea894997dd4eb0:out,NaN,NaN,1474975662635,17071,17071_9e72b06c707cb4103ec1c4c5873b5812,2016-09-27 20:27:42
43,out,NaN,b10a396ccc34745efb5a701f1dbe99ba,38,786:7fea8949980a6eb6:out,NaN,NaN,1474975661913,17071,17071_b10a396ccc34745efb5a701f1dbe99ba,2016-09-27 20:27:41
45,out,NaN,09f9204dbd027d2685f30434af245f62,506,786:7fea89499ae2dd77:out,NaN,NaN,1474975650258,17071,17071_09f9204dbd027d2685f30434af245f62,2016-09-27 20:27:30
47,out,NaN,8d27efedc7f18f77493cf6408b360c68,393,786:7fea89499bd88d09:out,NaN,NaN,1474975646327,17071,17071_8d27efedc7f18f77493cf6408b360c68,2016-09-27 20:27:26
48,out,NaN,a8b286e6557a9161dca878525c761ba8,681,786:7fea89499c1a6c78:out,NaN,NaN,1474975645273,17071,17071_a8b286e6557a9161dca878525c761ba8,2016-09-27 20:27:25
49,out,NaN,0f241275fc286929662bb4b17ca26b40,2,786:7fea89499d342f7f:out,NaN,NaN,1474975640765,17071,17071_0f241275fc286929662bb4b17ca26b40,2016-09-27 20:27:20
51,out,NaN,9dcf31e73473aa44f40208cd406e896f,120,786:7fea89499e352f46:out,NaN,NaN,1474975636653,17071,17071_9dcf31e73473aa44f40208cd406e896f,2016-09-27 20:27:16
54,out,NaN,a1bba2f4c777010f2bf35e01d337366d,21,786:7fea8949a9dfbfd3:out,NaN,NaN,1474975588868,17071,17071_a1bba2f4c777010f2bf35e01d337366d,2016-09-27 20:26:28
55,out,NaN,f2660fb1c6a60b04eb7582f24e58ee0b,68,786:7fea8949aafe4f96:out,NaN,NaN,1474975584283,17071,17071_f2660fb1c6a60b04eb7582f24e58ee0b,2016-09-27 20:26:24
60,out,NaN,4c2fb8be1bb68d540c27ce9bdd06729c,41,786:7fea8949b7bf5ed4:out,NaN,NaN,1474975532042,17071,17071_4c2fb8be1bb68d540c27ce9bdd06729c,2016-09-27 20:25:32
62,out,NaN,2d3d5a1375d0dedcc1977f0e49d1c741,13,786:7fea8949c33acc29:out,NaN,NaN,1474975485011,17071,17071_2d3d5a1375d0dedcc1977f0e49d1c741,2016-09-27 20:24:45
63,out,NaN,cce12bfadde13fd0e9a9e509ecf53880,624,786:7fea8949c4276db2:out,NaN,NaN,1474975481225,17071,17071_cce12bfadde13fd0e9a9e509ecf53880,2016-09-27 20:24:41
65,out,NaN,f867838b4b668fb71bda10b46c5214da,3,786:7fea8949c7525c4f:out,NaN,NaN,1474975468250,17071,17071_f867838b4b668fb71bda10b46c5214da,2016-09-27 20:24:28
67,out,NaN,bd1f19360bc63283cff654226fa1bb31,3,786:7fea8949cbf90ec3:out,NaN,NaN,1474975449199,17071,17071_bd1f19360bc63283cff654226fa1bb31,2016-09-27 20:24:09
69,out,NaN,92191cc2b670aee68b8361cdcd669533,2,786:7fea8949cc066dbe:out,NaN,NaN,1474975448985,17071,17071_92191cc2b670aee68b8361cdcd669533,2016-09-27 20:24:08
...,...,...,...,...,...,...,...,...,...,...,...
49924,out,NaN,10ad9d7773c98db5aec633d9b90dbb71,30,786:7fea8aa248fb9ede:out,NaN,NaN,1474614227014,17067,17067_10ad9d7773c98db5aec633d9b90dbb71,2016-09-23 16:03:47
49926,out,NaN,d8163cfe02f776818b4120d7b2e48b64,84,786:7fea8aa24938bed7:out,NaN,NaN,1474614226036,17067,17067_d8163cfe02f776818b4120d7b2e48b64,2016-09-23 16:03:46
49927,out,NaN,922b77aaf6334a0efd6f3877af844608,544,786:7fea8aa2493f9ddc:out,NaN,NaN,1474614225926,17067,17067_922b77aaf6334a0efd6f3877af844608,2016-09-23 16:03:45
49928,out,NaN,04dda673a0b8bf6aef86339f4b100b2c,79,786:7fea8aa249a4bfd2:out,NaN,NaN,1474614224308,17067,17067_04dda673a0b8bf6aef86339f4b100b2c,2016-09-23 16:03:44
49932,out,NaN,2947472b023f4b4fb1602502214f0d71,6,786:7fea8aa24d898c45:out,NaN,NaN,1474614208359,17067,17067_2947472b023f4b4fb1602502214f0d71,2016-09-23 16:03:28
49933,out,NaN,77d0bb2c2dbaea16c570365666e1938d,747,786:7fea8aa24f960f3f:out,1.0,65.0,1474614199967,17067,17067_77d0bb2c2dbaea16c570365666e1938d,2016-09-23 16:03:19
49937,out,NaN,fdc0943ef2311dd61398d6932c3785b9,1082,786:7fea8aa25094ad42:out,NaN,NaN,1474614195893,17067,17067_fdc0943ef2311dd61398d6932c3785b9,2016-09-23 16:03:15
49939,out,NaN,07ead047ae149b83a9e146fab2123bb8,3,786:7fea8aa252539c8a:out,NaN,NaN,1474614188742,17067,17067_07ead047ae149b83a9e146fab2123bb8,2016-09-23 16:03:08
49942,out,NaN,76e424704eccb786e13dc577541e6e5a,455,786:7fea8aa259f55fa7:out,NaN,NaN,1474614157482,17067,17067_76e424704eccb786e13dc577541e6e5a,2016-09-23 16:02:37
49944,out,NaN,8bd9d731f7f54af1448c387296bcbf8e,90,786:7fea8aa25c9dcdb5:out,25.0,1.0,1474614146595,17067,17067_8bd9d731f7f54af1448c387296bcbf8e,2016-09-23 16:02:26
49945,out,NaN,eef01aa6b1a857f4bc1936a7e7ae4208,36,786:7fea8aa263889e4a:out,2.0,46.0,1474614118262,17067,17067_eef01aa6b1a857f4bc1936a7e7ae4208,2016-09-23 16:01:58
49946,out,NaN,a296a628514d28a1db46f797d6b97f36,197,786:7fea8aa265765f71:out,NaN,NaN,1474614110362,17067,17067_a296a628514d28a1db46f797d6b97f36,2016-09-23 16:01:50
49953,out,NaN,6e296c20f9b3d27aaddaaded4716dc50,8,786:7fea8aa26c981f8d:out,3.0,1.0,1474614081150,17067,17067_6e296c20f9b3d27aaddaaded4716dc50,2016-09-23 16:01:21
49955,out,NaN,ec47e48a8b1582d6b247675a997bc73c,28,786:7fea8aa26e89fdb3:out,NaN,NaN,1474614073184,17067,17067_ec47e48a8b1582d6b247675a997bc73c,2016-09-23 16:01:13
49956,out,NaN,fa2e8e7cb3816926ba3af294f281e1f7,5,786:7fea8aa26f7f9f7b:out,NaN,NaN,1474614069254,17067,17067_fa2e8e7cb3816926ba3af294f281e1f7,2016-09-23 16:01:09
49962,out,NaN,d7cc40d8b88a46b50aa7d560e03336a5,145,786:7fea8aa270db8f0d:out,NaN,NaN,1474614063687,17067,17067_d7cc40d8b88a46b50aa7d560e03336a5,2016-09-23 16:01:03
49966,out,NaN,e42c9ae87da36e5fe655c3c3f355044b,172,786:7fea8aa272004c61:out,NaN,NaN,1474614059003,17067,17067_e42c9ae87da36e5fe655c3c3f355044b,2016-09-23 16:00:59
49972,out,NaN,c0b54a47aba213a62d15e1ac77ec77e5,5,786:7fea8aa2749c6c9b:out,NaN,NaN,1474614048313,17067,17067_c0b54a47aba213a62d15e1ac77ec77e5,2016-09-23 16:00:48
49980,out,NaN,ab23ee76b63440c1f7da7754e4198a5d,174,786:7fea8aa27b075e95:out,1.0,6.0,1474614022026,17067,17067_ab23ee76b63440c1f7da7754e4198a5d,2016-09-23 16:00:22
49981,out,NaN,73975a83c904d1ac14ac004aa6c8bebc,12,786:7fea8aa27ca70ed2:out,NaN,NaN,1474614015375,17067,17067_73975a83c904d1ac14ac004aa6c8bebc,2016-09-23 16:00:15
49982,out,NaN,3829327cb532db77f69e0fc8a369e828,20,786:7fea8aa27cff7cce:out,NaN,NaN,1474614013960,17067,17067_3829327cb532db77f69e0fc8a369e828,2016-09-23 16:00:13
49986,out,NaN,43809073fe825d6964c049c71182e0f4,15,786:7fea8aa2851c2dd9:out,NaN,NaN,1474613980733,17067,17067_43809073fe825d6964c049c71182e0f4,2016-09-23 15:59:40
49988,out,NaN,004544886dd834b453344f0da916aff6,11,786:7fea8aa287a97f94:out,1.0,2.0,1474613970280,17067,17067_004544886dd834b453344f0da916aff6,2016-09-23 15:59:30
49991,out,NaN,ba1a4cfd942b4d837ee4e10a6d025e1d,139,786:7fea8aa28e372edd:out,NaN,NaN,1474613943437,17067,17067_ba1a4cfd942b4d837ee4e10a6d025e1d,2016-09-23 15:59:03
49992,1f-left,NaN,34f95176a5712ab935f65c12bdb0ea52,45,786:7fea8aa291c55f3e:1f-left,NaN,NaN,1474613928874,17067,17067_34f95176a5712ab935f65c12bdb0ea52,2016-09-23 15:58:48
49993,1f-inner,NaN,34f95176a5712ab935f65c12bdb0ea52,92,786:7fea8aa291cfbef7:1f-inner,NaN,NaN,1474613928708,17067,17067_34f95176a5712ab935f65c12bdb0ea52,2016-09-23 15:58:48
49994,1f,NaN,34f95176a5712ab935f65c12bdb0ea52,92,786:7fea8aa291fe9efc:1f,NaN,NaN,1474613927958,17067,17067_34f95176a5712ab935f65c12bdb0ea52,2016-09-23 15:58:47
49995,in,NaN,34f95176a5712ab935f65c12bdb0ea52,92,786:7fea8aa291fe9efc:in,NaN,NaN,1474613927958,17067,17067_34f95176a5712ab935f65c12bdb0ea52,2016-09-23 15:58:47
49997,out,NaN,fa1d4f14701948f4d9713a6a32b1ebc9,63,786:7fea8aa292bc9ced:out,5.0,17.0,1474613924918,17067,17067_fa1d4f14701948f4d9713a6a32b1ebc9,2016-09-23 15:58:44
49998,out,NaN,260d605126f99d4fbfd3b8c1093df973,3,786:7fea8aa294b7fd07:out,NaN,NaN,1474613916800,17067,17067_260d605126f99d4fbfd3b8c1093df973,2016-09-23 15:58:36

In [74]:
i = 40
df2[i:i+50][['device_id', 'area', 'dwell_time', 'ts_start']]

,device_id,area,dwell_time,ts_start
2895,8b7c08b5c9795400d7ae2bbe8b1be410,2f-right,10,2016-09-27 16:50:21
2896,8b7c08b5c9795400d7ae2bbe8b1be410,in,10,2016-09-27 16:50:21
2970,07efe7f0724f4ade616c11768258cb1c,1f,115,2016-09-27 16:45:22
2971,07efe7f0724f4ade616c11768258cb1c,1f-right,2,2016-09-27 16:45:22
2972,07efe7f0724f4ade616c11768258cb1c,in,115,2016-09-27 16:45:22
3445,3152692afe8ff0e5715aacb89ab92ef4,1f,5,2016-09-27 16:08:30
3462,3152692afe8ff0e5715aacb89ab92ef4,in,81,2016-09-27 16:07:14
3831,4c676782d37f8f3512ca0e563abc6bd6,1f,7,2016-09-27 15:31:15
3832,4c676782d37f8f3512ca0e563abc6bd6,in,7,2016-09-27 15:31:15
4036,158c04751bcda6dd0326fdb5bb210634,1f,2,2016-09-27 15:18:33
4037,158c04751bcda6dd0326fdb5bb210634,in,2,2016-09-27 15:18:33
4743,0b435eaa07b9373f05637cf8b03a8da2,2f,38,2016-09-27 14:22:47
4745,0b435eaa07b9373f05637cf8b03a8da2,in,38,2016-09-27 14:22:47
4970,07efe7f0724f4ade616c11768258cb1c,1f,30,2016-09-27 14:05:54
4971,07efe7f0724f4ade616c11768258cb1c,in,30,2016-09-27 14:05:54
5011,8f4e27fd5639b469500efedaaa933ec5,1f,170,2016-09-27 14:02:56
5036,8f4e27fd5639b469500efedaaa933ec5,in,256,2016-09-27 14:01:30
5216,de12dccd21897a9d433ecfef28afdf63,1f-right,455,2016-09-27 13:46:03
5217,de12dccd21897a9d433ecfef28afdf63,1f,574,2016-09-27 13:46:03
5283,de12dccd21897a9d433ecfef28afdf63,in,895,2016-09-27 13:40:43
5312,07efe7f0724f4ade616c11768258cb1c,1f-inner,283,2016-09-27 13:38:02
5313,07efe7f0724f4ade616c11768258cb1c,1f-left,590,2016-09-27 13:37:59
5314,07efe7f0724f4ade616c11768258cb1c,1f,602,2016-09-27 13:37:57
5315,07efe7f0724f4ade616c11768258cb1c,1f-right,602,2016-09-27 13:37:57
5316,07efe7f0724f4ade616c11768258cb1c,in,602,2016-09-27 13:37:57
5373,a1bba2f4c777010f2bf35e01d337366d,in,83,2016-09-27 13:33:33
5382,a929327a342b73653547b9ce57eba9a7,1f,3,2016-09-27 13:33:18
5383,a929327a342b73653547b9ce57eba9a7,in,3,2016-09-27 13:33:18
5389,268eac5b638caea26f795a8fbd5da92b,1f,111,2016-09-27 13:33:05
5390,268eac5b638caea26f795a8fbd5da92b,1f-right,45,2016-09-27 13:33:05
5391,268eac5b638caea26f795a8fbd5da92b,in,111,2016-09-27 13:33:05
5634,de12dccd21897a9d433ecfef28afdf63,1f-right,764,2016-09-27 13:15:35
5635,de12dccd21897a9d433ecfef28afdf63,1f,784,2016-09-27 13:15:34
5636,de12dccd21897a9d433ecfef28afdf63,in,784,2016-09-27 13:15:34
5704,ee70e42e0385b0991b156a593e605e59,1f-right,266,2016-09-27 13:10:34
5709,ee70e42e0385b0991b156a593e605e59,1f,298,2016-09-27 13:10:12
5777,ee70e42e0385b0991b156a593e605e59,in,617,2016-09-27 13:04:53
5797,3e6d2d72e4adda00d4fa3349be12c0b0,1f-inner,361,2016-09-27 13:03:05
5800,c0aedde403ccf542ac0dfbf70bb546e5,1f,371,2016-09-27 13:02:54
5801,c0aedde403ccf542ac0dfbf70bb546e5,in,371,2016-09-27 13:02:54
5810,3e6d2d72e4adda00d4fa3349be12c0b0,1f-left,372,2016-09-27 13:01:59
5838,3e6d2d72e4adda00d4fa3349be12c0b0,1f,677,2016-09-27 13:00:30
5839,3e6d2d72e4adda00d4fa3349be12c0b0,1f-right,515,2016-09-27 13:00:30
6038,788bcf0af8e410d5907caaa3a41b31c8,1f,2,2016-09-27 12:43:39
6039,788bcf0af8e410d5907caaa3a41b31c8,in,2,2016-09-27 12:43:39
6149,3e6d2d72e4adda00d4fa3349be12c0b0,3f,142,2016-09-27 12:35:41
6189,3e6d2d72e4adda00d4fa3349be12c0b0,1f-inner,67,2016-09-27 12:32:02
6201,c0aedde403ccf542ac0dfbf70bb546e5,1f,122,2016-09-27 12:30:49
6203,c0aedde403ccf542ac0dfbf70bb546e5,in,122,2016-09-27 12:30:49
6208,3e6d2d72e4adda00d4fa3349be12c0b0,1f-right,207,2016-09-27 12:30:24

In [ ]:
uids = df2[i:i+50][['device_id', 'area', 'dwell_time', 'ts_start']].device_id.unique()

In [73]:
df.loc[df.device_id==uids[4]]

,area,deny,device_id,dwell_time,key,revisit_count,revisit_period,ts,date,date_device_id,ts_start
4036,1f,NaN,158c04751bcda6dd0326fdb5bb210634,2,786:7fea895b4888cdc9:1f,NaN,NaN,1474957113203,17071,17071_158c04751bcda6dd0326fdb5bb210634,2016-09-27 15:18:33
4037,in,NaN,158c04751bcda6dd0326fdb5bb210634,2,786:7fea895b4888cdc9:in,1.0,22.0,1474957113203,17071,17071_158c04751bcda6dd0326fdb5bb210634,2016-09-27 15:18:33
4038,out,NaN,158c04751bcda6dd0326fdb5bb210634,60,786:7fea895b4e59ddb7:out,1.0,22.0,1474957089378,17071,17071_158c04751bcda6dd0326fdb5bb210634,2016-09-27 15:18:09
37805,out,NaN,158c04751bcda6dd0326fdb5bb210634,656,786:7fea8a51a2be9e12:out,1.0,19.0,1474698794006,17068,17068_158c04751bcda6dd0326fdb5bb210634,2016-09-24 15:33:14
38089,out,NaN,158c04751bcda6dd0326fdb5bb210634,35,786:7fea8a529c438d4e:out,1.0,19.0,1474697771975,17068,17068_158c04751bcda6dd0326fdb5bb210634,2016-09-24 15:16:11